# Generated by Django 6.1 on 2026-09-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0005_sujet_formation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name='nom')),
                ('organisation', models.CharField(blank=True, max_length=160, verbose_name='organisation')),
                ('fonction', models.CharField(blank=True, max_length=120, verbose_name='fonction')),
                ('courriel', models.EmailField(blank=True, max_length=254, verbose_name='courriel')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='commune')),
                ('produit', models.CharField(choices=[('isidor', 'Isidor'), ('vanessa', 'Vanessa'), ('bernard', 'Bernard'), ('katarina', 'Katarina'), ('conseil', 'Conseil'), ('formation', 'Formation'), ('autre', 'À qualifier')], default='autre', max_length=20, verbose_name='produit')),
                ('statut', models.CharField(choices=[('lead', 'Lead'), ('contacte', 'Contacté'), ('demo', 'Démo'), ('proposition', 'Proposition'), ('client', 'Client'), ('perdu', 'Perdu')], default='lead', max_length=20, verbose_name='étape')),
                ('source', models.CharField(choices=[('site', 'Formulaire du site'), ('appel', 'Appel entrant'), ('recommandation', 'Recommandation'), ('salon', 'Salon, événement'), ('linkedin', 'LinkedIn'), ('prospection', 'Prospection'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='source')),
                ('taille', models.PositiveIntegerField(blank=True, help_text='Hectares pour Isidor, habitants pour Vanessa, biens gérés pour Bernard…', null=True, verbose_name='taille')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text="Vide pour Isidor : calculé d'après la surface et le tarif public.", max_digits=10, null=True, verbose_name='montant estimé (€ HT par an)')),
                ('prochaine_relance', models.DateField(blank=True, null=True, verbose_name='prochaine relance')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='pages.demandedemonstration', verbose_name="demande d'origine")),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contact',
                'ordering': ('-modifie_le',),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('note', 'Note'), ('appel', 'Appel'), ('rendez_vous', 'Rendez-vous'), ('mail', 'Mail'), ('etape', "Changement d'étape")], default='note', max_length=20)),
                ('texte', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'échange',
                'ordering': ('-cree_le',),
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['produit', 'statut'], name='contact_pipeline_idx'),
        ),
    ]
