# Generated by Django 6.1 on 2026-09-17 09:35

from django.conf import settings
from django.db import migrations, models

SOURCES_SORTANTES = ("prospection", "linkedin", "salon")


def classer(apps, schema_editor):
    """Les contacts déjà saisis sont rangés d'après leur source : démarchés d'un côté,
    venus à nous de l'autre (valeur par défaut du champ)."""
    Contact = apps.get_model("contacts", "Contact")
    Contact.objects.filter(source__in=SOURCES_SORTANTES).update(sens="sortant")


def tout_entrant(apps, schema_editor):
    apps.get_model("contacts", "Contact").objects.update(sens="entrant")


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_import_demandes'),
        ('pages', '0005_sujet_formation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sens',
            field=models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], default='entrant', help_text="Entrant : la personne est venue à nous. Sortant : c'est nous qui la démarchons.", max_length=10, verbose_name='origine'),
        ),
        migrations.RunPython(classer, tout_entrant),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['sens', 'statut'], name='contact_sens_idx'),
        ),
    ]
