# Generated by Django 6.1 on 2026-09-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_sens'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_contact',
            field=models.DateField(blank=True, null=True, verbose_name='contacté le'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_naissance',
            field=models.DateField(blank=True, help_text="Sert à afficher l'âge dans le tableau.", null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_reponse',
            field=models.DateField(blank=True, null=True, verbose_name='réponse le'),
        ),
        migrations.AddField(
            model_name='contact',
            name='departement',
            field=models.CharField(blank=True, max_length=80, verbose_name='département'),
        ),
        migrations.AddField(
            model_name='contact',
            name='prenom',
            field=models.CharField(blank=True, max_length=80, verbose_name='prénom'),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, max_length=80, verbose_name='région'),
        ),
    ]
