# Generated by Django 6.0.5 on 2026-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction')),
                ('commune', models.CharField(max_length=200, verbose_name='Commune ou intercommunalité')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('consentement_rgpd', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-cree_le'],
            },
        ),
    ]
