# Generated by Django 6.1 on 2026-09-12 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('rendez_vous', 'Rendez-vous client'), ('formation', 'Formation'), ('deploiement', 'Déploiement'), ('interne', 'Interne'), ('autre', 'Autre')], default='rendez_vous', max_length=20, verbose_name='catégorie')),
                ('debut', models.DateTimeField(db_index=True, verbose_name='début')),
                ('fin', models.DateTimeField()),
                ('journee_entiere', models.BooleanField(default=False, verbose_name='journée entière')),
                ('organisation', models.CharField(blank=True, max_length=160, verbose_name='client ou organisation')),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('lien_visio', models.URLField(blank=True, verbose_name='lien visio')),
                ('description', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='evenements_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "événement d'agenda",
                'verbose_name_plural': "événements d'agenda",
                'ordering': ('debut',),
            },
        ),
    ]
