# Generated by Django 6.1 on 2026-08-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDemonstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('collectivite', models.CharField(max_length=160, verbose_name='collectivité')),
                ('fonction', models.CharField(blank=True, max_length=120, verbose_name='fonction')),
                ('courriel', models.EmailField(max_length=254, verbose_name='courriel')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='reçue le')),
                ('traitee', models.BooleanField(default=False, verbose_name='traitée')),
            ],
            options={
                'verbose_name': 'demande de démonstration',
                'verbose_name_plural': 'demandes de démonstration',
                'ordering': ['-cree_le'],
            },
        ),
    ]
