# Generated by Django 6.1 on 2026-09-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedemonstration',
            name='rappel_heure',
            field=models.TimeField(blank=True, null=True, verbose_name='heure de rappel'),
        ),
        migrations.AddField(
            model_name='demandedemonstration',
            name='rappel_jour',
            field=models.DateField(blank=True, null=True, verbose_name='jour de rappel'),
        ),
    ]
