# Generated by Django 6.1 on 2026-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_organisation_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedemonstration',
            name='sujet',
            field=models.CharField(choices=[('conseil', "Conseil (IA, data, systèmes d'information)"), ('isidor', 'Isidor — agriculture'), ('katarina', "Katarina — chambres d'agriculture"), ('vanessa', 'Vanessa — mairies'), ('bernard', 'Bernard — immobilier'), ('autre', 'Autre demande')], default='autre', max_length=20, verbose_name='sujet'),
        ),
    ]
