# Generated by Django 6.1 on 2026-09-11 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visiteur', models.CharField(blank=True, max_length=16)),
                ('chemin', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('telephone', 'Clic sur le téléphone'), ('courriel', 'Clic sur le courriel'), ('appel_action', "Clic sur un appel à l'action"), ('sortant', 'Lien sortant'), ('faq', 'Question de FAQ ouverte'), ('dictee', 'Dictée vocale lancée'), ('reformulation', "Reformulation par l'IA"), ('connexion', "Connexion à l'espace client"), ('telechargement', 'Document téléchargé')], db_index=True, max_length=20)),
                ('cible', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chemin', models.CharField(db_index=True, max_length=300)),
                ('visiteur', models.CharField(db_index=True, max_length=16)),
                ('temps_actif_s', models.PositiveIntegerField(default=0)),
                ('defilement', models.PositiveSmallIntegerField(default=0)),
                ('lcp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('inp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('fcp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ttfb_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mesure de page',
                'verbose_name_plural': 'mesures de page',
            },
        ),
        migrations.CreateModel(
            name='PageVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chemin', models.CharField(db_index=True, max_length=300)),
                ('statut', models.PositiveSmallIntegerField(default=200)),
                ('visiteur', models.CharField(db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('direct', 'Accès direct'), ('moteur', 'Moteurs de recherche'), ('ia', 'Assistants IA'), ('social', 'Réseaux sociaux'), ('site', 'Sites référents'), ('campagne', 'Campagnes'), ('interne', 'Navigation interne')], default='direct', max_length=10)),
                ('referent', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campagne', models.CharField(blank=True, max_length=80)),
                ('appareil', models.CharField(blank=True, max_length=12)),
                ('navigateur', models.CharField(blank=True, max_length=30)),
                ('systeme', models.CharField(blank=True, max_length=30)),
                ('langue', models.CharField(blank=True, max_length=10)),
                ('duree_serveur_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'page vue',
                'verbose_name_plural': 'pages vues',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='PassageRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('robot', models.CharField(max_length=40)),
                ('famille', models.CharField(choices=[('ia', "Robots d'IA"), ('moteur', 'Moteurs de recherche'), ('autre', 'Autres robots')], max_length=10)),
                ('chemin', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'passage de robot',
                'verbose_name_plural': 'passages de robots',
            },
        ),
    ]
