# Generated by Django 6.1 on 2026-09-11 22:04

import django.core.validators
import django.db.models.deletion
import espace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160, verbose_name='titre')),
                ('type', models.CharField(choices=[('conseil', 'Mission de conseil'), ('formation', 'Formation'), ('logiciel', 'Déploiement de logiciel')], max_length=20, verbose_name='type')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20, verbose_name='statut')),
                ('avancement', models.PositiveSmallIntegerField(default=0, help_text='En pourcentage, de 0 à 100.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='avancement')),
                ('prochaine_etape', models.CharField(blank=True, max_length=200, verbose_name='prochaine étape')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='fin prévue')),
                ('mis_a_jour', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-mis_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160, verbose_name='titre')),
                ('categorie', models.CharField(choices=[('facture', 'Facture'), ('livrable', 'Livrable'), ('attestation', 'Attestation'), ('autre', 'Autre document')], default='autre', max_length=20, verbose_name='catégorie')),
                ('fichier', models.FileField(storage=espace.models.StockagePrive(), upload_to=espace.models.chemin_document, verbose_name='fichier')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='espace.projet', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-ajoute_le'],
            },
        ),
    ]
