# Generated by Django 6.1 on 2026-09-12 09:53

import courriel.models
import django.db.models.deletion
import espace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteCourriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, help_text="Par exemple « Contact ». Vide : l'adresse est affichée.", max_length=80, verbose_name='libellé')),
                ('adresse', models.EmailField(max_length=254, unique=True, verbose_name='adresse')),
                ('nom_expediteur', models.CharField(default='Satkaar', max_length=80, verbose_name='nom affiché aux destinataires')),
                ('identifiant', models.CharField(help_text="Souvent l'adresse elle-même.", max_length=255, verbose_name='identifiant')),
                ('mot_de_passe_chiffre', models.BinaryField(default=b'')),
                ('imap_hote', models.CharField(max_length=120, verbose_name='serveur IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='port IMAP')),
                ('smtp_hote', models.CharField(max_length=120, verbose_name='serveur SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=465, verbose_name='port SMTP')),
                ('smtp_securite', models.CharField(choices=[('ssl', 'SSL/TLS (port 465)'), ('starttls', 'STARTTLS (port 587)')], default='ssl', max_length=10, verbose_name='sécurité SMTP')),
                ('signature', models.TextField(blank=True, help_text='Ajoutée sous chaque nouveau message, réponse et transfert.')),
                ('actif', models.BooleanField(default=True, verbose_name='relever cette boîte')),
                ('derniere_releve', models.DateTimeField(blank=True, null=True, verbose_name='dernière relève')),
                ('derniere_erreur', models.CharField(blank=True, max_length=300)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'boîte mail',
                'verbose_name_plural': 'boîtes mail',
                'ordering': ('libelle', 'adresse'),
            },
        ),
        migrations.CreateModel(
            name='Courriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(choices=[('reception', 'Boîte de réception'), ('envoyes', 'Envoyés')], default='reception', max_length=10)),
                ('message_id', models.CharField(max_length=512)),
                ('uid', models.CharField(blank=True, max_length=40, verbose_name='UID IMAP')),
                ('expediteur_nom', models.CharField(blank=True, max_length=255)),
                ('expediteur_adresse', models.CharField(blank=True, max_length=255)),
                ('destinataires', models.TextField(blank=True)),
                ('copie', models.TextField(blank=True)),
                ('repondre_a', models.CharField(blank=True, max_length=255)),
                ('sujet', models.CharField(blank=True, max_length=500)),
                ('texte', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('date', models.DateTimeField(db_index=True)),
                ('en_reponse_a', models.CharField(blank=True, max_length=512)),
                ('references', models.TextField(blank=True)),
                ('lu', models.BooleanField(default=False)),
                ('etoile', models.BooleanField(default=False, verbose_name='étoilé')),
                ('corbeille', models.BooleanField(default=False)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courriels', to='courriel.comptecourriel')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'courriel',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_mime', models.CharField(default='application/octet-stream', max_length=120)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('fichier', models.FileField(storage=espace.models.StockagePrive(), upload_to=courriel.models.chemin_piece_jointe)),
                ('courriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courriel.courriel')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
        migrations.AddIndex(
            model_name='courriel',
            index=models.Index(fields=['compte', 'dossier', 'corbeille', '-date'], name='courriel_liste_idx'),
        ),
        migrations.AddConstraint(
            model_name='courriel',
            constraint=models.UniqueConstraint(fields=('compte', 'dossier', 'message_id'), name='courriel_unique_par_dossier'),
        ),
    ]
