# Generated by Django 6.1 on 2026-09-17 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courriel',
            name='categorie',
            field=models.CharField(choices=[('principale', 'Principale'), ('promotions', 'Promotions'), ('reseaux', 'Réseaux sociaux'), ('notifications', 'Notifications')], default='principale', max_length=15, verbose_name='catégorie'),
        ),
        migrations.AddIndex(
            model_name='courriel',
            index=models.Index(fields=['dossier', 'categorie', 'corbeille', '-date'], name='courriel_onglet_idx'),
        ),
    ]
