# Generated by Django 6.1 on 2026-09-17 01:12

import django.db.models.deletion
from django.db import migrations, models


def reprendre(apps, schema_editor):
    """La signature enregistrée sur chaque boîte devient sa signature par défaut."""
    CompteCourriel = apps.get_model("courriel", "CompteCourriel")
    Signature = apps.get_model("courriel", "Signature")
    for compte in CompteCourriel.objects.exclude(signature=""):
        Signature.objects.create(compte=compte, libelle=f"Signature {compte.libelle or compte.adresse}",
                                 corps=compte.signature, par_defaut=True)


def rendre(apps, schema_editor):
    CompteCourriel = apps.get_model("courriel", "CompteCourriel")
    Signature = apps.get_model("courriel", "Signature")
    for signature in Signature.objects.filter(par_defaut=True).exclude(compte=None):
        CompteCourriel.objects.filter(pk=signature.compte_id).update(signature=signature.corps)


class Migration(migrations.Migration):

    dependencies = [
        ('courriel', '0002_courriel_categorie_courriel_courriel_onglet_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Pour la reconnaître : « Direction », « Support »…', max_length=80, verbose_name='nom')),
                ('corps', models.TextField(help_text='Ajoutée sous « -- », au bas du message.', verbose_name='signature')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='proposée par défaut')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(blank=True, help_text='Vide : proposée pour toutes les boîtes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='courriel.comptecourriel', verbose_name='boîte')),
            ],
            options={
                'verbose_name': 'signature',
                'ordering': ('-par_defaut', 'libelle'),
            },
        ),
        migrations.RunPython(reprendre, rendre),
        migrations.RemoveField(
            model_name='comptecourriel',
            name='signature',
        ),
    ]
