# Generated by Django 6.1 on 2026-09-17 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriel', '0003_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Pour le reconnaître : « Première approche mairie »…', max_length=80, verbose_name='nom')),
                ('sujet', models.CharField(blank=True, max_length=500, verbose_name='objet')),
                ('corps', models.TextField(help_text='Mise en forme conservée. Repères : {prenom}, {nom}, {organisation}, {ville}.', verbose_name='message')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(blank=True, help_text='Vide : proposé pour toutes les boîtes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='courriel.comptecourriel', verbose_name='boîte')),
            ],
            options={
                'verbose_name': 'modèle de message',
                'verbose_name_plural': 'modèles de message',
                'ordering': ('libelle',),
            },
        ),
    ]
